"use client";
import { useState } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";
import { SafeComponent } from "@/components/SafeComponent";

const Accordion = ({ title, content }: { title: string; content: string }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="mb-4 border-2 border-(--border-color) bg-(--background) rounded-2xl overflow-hidden transition-all shadow-sm">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full py-5 px-6 flex items-center justify-between text-left hover:opacity-80 transition-all cursor-pointer"
      >
        <span className="text-xs font-light uppercase tracking-[0.2em] text-(--foreground)">
          {title}
        </span>
        <div className="text-(--foreground)">
          {isOpen ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
        </div>
      </button>
      <div className={`transition-all duration-300 ${isOpen ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'}`}>
        <div className="px-6 pb-6 pt-2 border-t border-(--border-color)">
          <p className="text-sm leading-relaxed font-medium text-(--foreground) opacity-80">
            {content}
          </p>
        </div>
      </div>
    </div>
  );
};

export default function TermsPage() {
  return (
    <SafeComponent name="TermsPage">
      <div className="max-w-4xl mx-auto py-12 px-4 text-center">
        <h1 className="text-5xl md:text-8xl font-light tracking-[-0.07em] uppercase leading-none text-(--foreground) mb-16">
          TERMS
        </h1>

        <div className="max-w-2xl mx-auto text-left space-y-3">
          <Accordion title="Intellectual Property" content="Any content you generate is your IP & responsibility." />
          <Accordion title="Privacy Policy" content="We respect your data. We do not collect or sell your personal information." />
          <Accordion title="Cookies" content="We use minor cookies to remember your theme preferences and secure your workstation session details." />
          <Accordion title="AI Usage" content="We use artificial intelligence to assist in building applications. Please note: AI can make mistakes and the generated applications might not be as expected. Users are responsible for their generated content and Optimize Maximal AI does not take any responsibility for the code generated by users." />
          <Accordion title="All Rights Reserved" content="© 2026 Optimize Maximal AI. All Rights Reserved." />
        </div>
      </div>
    </SafeComponent>
  );
}